### ISSUE TITLE
Have the model summarized my own dataset

### ISSUE THREAD

**Issue by suchanun** [maszhongming/MatchSum#4]
Hi, I want to use your pre-trained model to generate summaries for my data, am I understand it right that I have to process my data according to the "processing you own data" section? If so,

1. Does my .jsonl file should contain all these parameters: 'label', 'text', 'summary', 'ext_idx', 'indices', 'score', 'candidate_id', 'text_id', 'summary_id' ?
2. Why do I need to select some important sentences and get index.jsonl ? (because what I want is for the model to select summary sentences for me)
3. What is index.jsonl file for?
4. The summary output of the model will go into my .jsonl file at the 'summary' field?

Thank you so much for any help!

**Comment by maszhongming** [comment]
Thank you for your interest in our work, as to your questions:
1. If you just want to test on your own dataset, your .jsonl file should contain at least the following fields: `text`, `indices`, `candidate_id`, and `text_id`.
2. The number of possible candidate summaries in a document can be very large, so we have to do some pruning operations. For example, there are 50 sentences in a document and you want to extract 3 of them to form a summary, the number of candidate summaries is C (50, 3) = 19600. But if you select 5 important sentences in the document first, the number of candidate summaries is only C(5, 3) = 10.
3. index.jsonl contains the index of the important sentences you selected for each document. 
4. The output of the model will be stored in the folder `./result`.

Update on question 1:
Sorry, your data still need to contain `summary` and `summary_id`, the reason is [here](https://github.com/maszhongming/MatchSum/issues/5).

**Comment by suchanun** [comment]
Thank you so much for your reply!

Did you only use PreSum for getting the candidate sentences?

I'm sad that I can't get the PreSum to work, I've been trying to use their dev branch with their pre-trained model but still stuck [here](https://github.com/nlpyang/PreSumm/issues/161#issuecomment-626188088). :(

**Comment by suchanun** [comment]
Thank you for your reply and the update!
